version: '3'
services:
  web:
    build: .
    command: sh -c "alembic upgrade head && uvicorn chat.main:app --reload --port=7000 --host=0.0.0.0"
    ports:
      - 7000:7000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5437:5432




# sudo systemctl restart docker.socket docker.service